#!/usr/bin/env python3
#
# Generated by Claude 4 Sonnet
#
"""
Transform one or moreclouds.json files to pub-mapfile format

This script reads all *.json files from a directory and combines their image lists.
It filters images that contain
"us-east-1-hourly" in their "dest" attribute. It then transforms these
images to match the pub-mapfile JSON structure and outputs them to multiple
timestamped files for three different regions: us-east-1, us-iso-east-1, and us-isob-east-1.

For each region, it creates two files:
- pub-mapfile-<timestamp>.json (main version)
- test-pub-mapfile-<timestamp>.json (test version with empty billing codes)

Files are organized in the directory structure: {output-dir}/{ami-adc-release-date}/{rhel-version}-{cloudx-jira}/{region}/

The script uses boto3 to describe AMIs and extract boot_mode information.
AWS credentials must be configured (via AWS CLI, environment variables,
or IAM roles) with permissions to describe EC2 images. Any AWS API errors
will display helpful error messages and exit gracefully.

Requirements:
    - boto3 (pip install boto3)
    - AWS credentials configured
    - EC2:DescribeImages permission

Usage:
    # Generate pub-mapfile from clouds.json files:
    python3 generate_pubmapfile.py --clouds-json-dir <directory> --cloudx-jira <jira-id> [--ami-adc-release-date YYYY-MM-DD] [--image-dir IMAGE_DIR] [--output-dir OUTPUT_DIR]

    # Combine existing pub-mapfile JSON files from multiple cloudx-jira releases:
    python3 generate_pubmapfile.py --combine-image-releases-path <release-directory>

Examples:
    # Generate pub-mapfile from clouds.json files:
    python3 generate_pubmapfile.py --clouds-json-dir stage/ --cloudx-jira CLOUDX-123
    # Creates files in: ./dist/pub-mapfile/{today's date}/rhel{version}-CLOUDX-123/{region}/

    python3 generate_pubmapfile.py --clouds-json-dir stage/ --cloudx-jira CLOUDX-123 --ami-adc-release-date 2024-12-01
    # Creates files in: ./dist/pub-mapfile/2024-12-01/rhel{version}-CLOUDX-123/{region}/

    ./generate_pubmapfile.py --clouds-json-dir /path/to/json/files --cloudx-jira CLOUDX-456 --image-dir /path/to/images --output-dir ./output
    # Verifies MD5 checksums of image files in /path/to/images
    # Creates files in: ./output/{today's date}/rhel{version}-CLOUDX-456/{region}/

    # Combine existing pub-mapfile JSON files from multiple cloudx-jira releases:
    python3 generate_pubmapfile.py --combine-image-releases-path ./dist/pub-mapfile/2024-12-01
    # Combines all JSON files from rhel{version}-CLOUDX-* subdirectories
    # Creates combined files in: ./dist/pub-mapfile/2024-12-01/combined/{region}/
"""

import argparse
import glob
import hashlib
import json
import os
import re
import sys
from datetime import datetime
import boto3
from botocore.exceptions import ClientError, BotoCoreError
import copy
from cloudimg.aws import AWSBootMode


def calculate_checksum(file_path, hash_algorithm):
    """
    Calculate hash of a file using the specified algorithm.

    Args:
        file_path: Path to the file
        hash_algorithm: Hash algorithm instance (e.g., hashlib.md5(), hashlib.sha256())

    Returns:
        str: Hash in hexadecimal format

    Raises:
        FileNotFoundError: If file doesn't exist
        Exception: For other file access errors
    """
    try:
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(4096), b""):
                hash_algorithm.update(chunk)
        return hash_algorithm.hexdigest()
    except FileNotFoundError:
        raise FileNotFoundError(f"Image file not found: {file_path}")
    except Exception as e:
        raise Exception(f"Error reading file {file_path}: {e}")


def verify_checksum(image_src_filename, expected_md5):
    """
    Verify MD5 checksum of an image file and calculate SHA256.

    Args:
        image_src_filename: Full path to the image file
        expected_md5: Expected MD5 checksum from image metadata

    Returns:
        str: SHA256 checksum of the file

    Raises:
        SystemExit: If verification fails or MD5 is missing
    """
    if not expected_md5:
        print(f"Error: No MD5 checksum provided for {image_src_filename}, cannot verify image file integrity")
        sys.exit(1)

    try:
        # Calculate MD5 for verification
        calculated_md5 = calculate_checksum(image_src_filename, hashlib.md5())

        if calculated_md5.lower() != expected_md5.lower():
            print(f"Error: MD5 mismatch for {image_src_filename}")
            print(f"  Expected: {expected_md5}")
            print(f"  Calculated: {calculated_md5}")
            sys.exit(1)

        # Calculate SHA256 for pub-mapfile format
        return calculate_checksum(image_src_filename, hashlib.sha256())

    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


def get_ami_boot_mode(image_id, region='us-east-1'):
    """
    Describe an AMI using boto3 and return the AWSBootMode enum name.

    Args:
        image_id (str): The AMI ID to describe
        region (str): AWS region where the AMI is located

    Returns:
        str: The AWSBootMode enum name ('uefi', 'legacy', 'hybrid', or 'not_set')

    Note:
        If any AWS API errors occur, the script will print an informational
        message and exit gracefully.
    """
    try:
        # Create EC2 client for the specified region
        ec2_client = boto3.client('ec2', region_name=region)

        # Describe the AMI
        response = ec2_client.describe_images(ImageIds=[image_id])

        if response['Images']:
            image_info = response['Images'][0]
            boot_mode_enum = AWSBootMode(image_info.get('BootMode'))
            return boot_mode_enum.name
        else:
            print(f"Error: No AMI found with ID {image_id} in region {region}")
            print("Please verify the AMI ID and region are correct.")
            sys.exit(1)

    except ClientError as e:
        error_code = e.response['Error']['Code']
        if error_code == 'InvalidAMIID.NotFound':
            print(f"Error: AMI {image_id} not found in region {region}")
            print("Please verify the AMI ID exists in the specified region.")
        elif error_code == 'UnauthorizedOperation':
            print(f"Error: Not authorized to describe AMI {image_id} in region {region}")
            print("Please check your AWS credentials and permissions (EC2:DescribeImages required).")
        else:
            print(f"Error: AWS API error describing AMI {image_id}: {e}")
            print("Please check your AWS configuration and try again.")
        sys.exit(1)

    except Exception as e:
        print(f"Error: Unexpected error describing AMI {image_id}: {e}")
        print("Please check your AWS configuration, credentials, and network connectivity.")
        sys.exit(1)

def transform_image_to_pubmapfile_format(image, image_dir=None):
    """
    Transform a clouds.json image to pub-mapfile format.

    Args:
        image: Image object from clouds.json
        image_dir: Optional directory containing image files for MD5 verification
    """
    # Convert from absolute path to relative path format expected by pub-mapfile
    src_filename = os.path.basename(image.get('src'))
    # NOTE: image files are expected to be staged before running pubtools-adc-push
    # A stage directory with AWS_IMAGES directory is required by pubtool-adc-push
    relative_path = f"{image.get('region')}/AWS_IMAGES/{src_filename}"

    # Verify MD5 checksum if image_dir is provided and calculate SHA256
    sha256sum = None
    if image_dir:
        sha256sum = verify_checksum(os.path.join(image_dir, src_filename), image.get('md5sum'))

    boot_mode = get_ami_boot_mode(image.get('image_id'),
                                  image.get('region'))

    # Handle release version formatting - append ".0" if version is in "x.y" format
    release_info = copy.deepcopy(image.get('release', {}))
    if 'version' in release_info:
        version = release_info['version']
        # NOTE: patch version is hard-coded to 0 per
        #   https://gitlab.cee.redhat.com/stratosphere/starmap-mappings/-/merge_requests/139
        # Check if version matches "x.y" pattern (e.g., "9.4"), and convert to "x.y.z" format
        if re.match(r'^\d+\.\d+$', str(version)):
            release_info['version'] = f"{version}.0"

    # Handle base_product - expected to be null/empty, set to "import" to distinguish from built images
    base_product = release_info.get('base_product')
    if base_product is None or base_product == '':
        release_info['base_product'] = 'import'
    else:
        print(f"Error: release.base_product contains value '{base_product}' but we expect it to be null or empty")
        print("Expected base_product to be null/empty so it can be set to 'import'")
        sys.exit(1)

    # Create the transformed image object
    transformed = {
        "attributes": {
            "billing_codes": image.get('billing_codes'),
            "boot_mode": boot_mode,
            "description": image.get('description'),
            "ena_support": image.get('ena_support', True),
            "public_image": False,           # commercial images imported into ADC regions should never be public; they must be customized first
            "region": image.get('region', 'us-east-1'),
            "release": release_info,
            "root_device": image.get('root_device', ''),
            "sriov_net_support": image.get('sriov_net_support', ''),
            "type": image.get('type', 'hourly'),
            "virtualization": image.get('virtualization', ''),
            "volume": image.get('volume', '')
        },
        "filename": image.get('name', ''),   # NOTE: for reference only, image name is dynamically generated by pubtool-adc
        "sha256sum": sha256sum,
        "version": image.get('origin', ''),
        "relative_path": relative_path
    }

    # Print the metadata for the processed image
    version = transformed["attributes"]["release"].get("version", "unknown")
    release_variant = transformed["attributes"]["release"].get('variant', 'unknown')
    variant = "HiAvai" if release_variant == "HighAvailability" else release_variant
    arch = transformed["attributes"]["release"].get('arch', 'unknown')
    image_id = image.get('image_id', 'unknown')
    image_name = transformed.get('filename', 'unknown')
    print(f"Processed image:  {version}  {variant} {arch}  {image_id}  {image_name}")

    return transformed

def combine_json_files(combine_path):
    """
    Combine JSON files from multiple cloudx-jira directories into consolidated files per region.

    Args:
        combine_path: Path to directory containing {rhel-version}-{cloudx-jira} subdirectories
    """
    print(f"Combining JSON files from release directory: {combine_path}")

    # Check if the combine path exists
    if not os.path.exists(combine_path):
        print(f"Error: Directory {combine_path} does not exist")
        sys.exit(1)

    # Find all cloudx-jira subdirectories (pattern: rhel{version}-CLOUDX-{number})
    cloudx_dirs = []
    for item in os.listdir(combine_path):
        item_path = os.path.join(combine_path, item)
        if os.path.isdir(item_path) and re.match(r'^rhel\d+-CLOUDX-\d+$', item):
            cloudx_dirs.append(item_path)

    if not cloudx_dirs:
        print(f"Error: No cloudx-jira subdirectories found in {combine_path}")
        print("Expected directories matching pattern: rhel{version}-CLOUDX-{number}")
        sys.exit(1)

    print(f"Found {len(cloudx_dirs)} cloudx-jira directories:")
    for dir_path in cloudx_dirs:
        print(f"  {os.path.basename(dir_path)}")

    # Extract release date from combine_path for output filenames
    release_date = os.path.basename(os.path.normpath(combine_path))

    # Define regions to process
    regions = ["us-east-1", "us-iso-east-1", "us-isob-east-1"]

    # Process each region
    for region in regions:
        print(f"\nProcessing region: {region}")

        # Collect all pub-mapfile and test-pub-mapfile JSON files for this region
        pub_mapfiles = []
        test_pub_mapfiles = []

        for cloudx_dir in cloudx_dirs:
            region_dir = os.path.join(cloudx_dir, region)
            if not os.path.exists(region_dir):
                print(f"  Warning: Region directory {region_dir} does not exist, skipping")
                continue

            # Find JSON files in this region directory
            json_files = glob.glob(os.path.join(region_dir, "*.json"))
            cloudx_name = os.path.basename(cloudx_dir)

            for json_file in json_files:
                filename = os.path.basename(json_file)
                if filename.startswith("test-pub-mapfile-"):
                    test_pub_mapfiles.append((json_file, cloudx_name))
                elif filename.startswith("pub-mapfile-"):
                    pub_mapfiles.append((json_file, cloudx_name))

        if not pub_mapfiles and not test_pub_mapfiles:
            print(f"  No JSON files found for region {region}, skipping")
            continue

        print(f"  Found {len(pub_mapfiles)} pub-mapfile and {len(test_pub_mapfiles)} test-pub-mapfile files")

        # Combine pub-mapfile JSON files
        if pub_mapfiles:
            combined_pub_mapfile = combine_mapfile_jsons(pub_mapfiles)

        # Combine test-pub-mapfile JSON files
        if test_pub_mapfiles:
            combined_test_pub_mapfile = combine_mapfile_jsons(test_pub_mapfiles)

        # Create combined output directory
        combined_output_dir = os.path.join(combine_path, "combined", region)
        if not os.path.exists(combined_output_dir):
            os.makedirs(combined_output_dir)

        # Write combined files
        if pub_mapfiles and combined_pub_mapfile:
            output_path = os.path.join(combined_output_dir, f"pub-mapfile-combined-{release_date}.json")
            try:
                with open(output_path, 'w') as f:
                    json.dump(combined_pub_mapfile, f, indent=2)
                total_files = len(combined_pub_mapfile['payload']['files'])
                print(f"  Successfully created {output_path} with {total_files} combined image files")
            except Exception as e:
                print(f"  Error writing combined pub-mapfile for region {region}: {e}")

        if test_pub_mapfiles and combined_test_pub_mapfile:
            test_output_path = os.path.join(combined_output_dir, f"test-pub-mapfile-combined-{release_date}.json")
            try:
                with open(test_output_path, 'w') as f:
                    json.dump(combined_test_pub_mapfile, f, indent=2)
                total_files = len(combined_test_pub_mapfile['payload']['files'])
                print(f"  Successfully created {test_output_path} with {total_files} combined image files (test version)")
            except Exception as e:
                print(f"  Error writing combined test-pub-mapfile for region {region}: {e}")

def combine_mapfile_jsons(json_files_list):
    """
    Combine multiple mapfile JSON files into a single consolidated JSON.

    Args:
        json_files_list: List of tuples (json_file_path, cloudx_name)

    Returns:
        dict: Combined JSON structure
    """
    combined_files = []
    header = None

    for json_file_path, cloudx_name in json_files_list:
        try:
            with open(json_file_path, 'r') as f:
                data = json.load(f)

            # Store the header from the first file
            if header is None:
                header = data.get('header', {"version": "0.2"})

            # Collect files from this JSON
            payload_files = data.get('payload', {}).get('files', [])
            combined_files.extend(payload_files)

            #print(f"    Added {len(payload_files)} files from {cloudx_name}/{os.path.basename(json_file_path)}")

        except Exception as e:
            print(f"    Error reading {json_file_path}: {e}")
            continue

    # Create the combined JSON structure
    combined_json = {
        "header": header,
        "payload": {
            "files": combined_files
        }
    }

    return combined_json

def main():
    # Parse command-line arguments
    parser = argparse.ArgumentParser(
        description='Transform clouds.json files to pub-mapfile format OR combine existing pub-mapfile JSON files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate pub-mapfile from clouds.json files:
  %(prog)s --clouds-json-dir stage/ --cloudx-jira CLOUDX-123
  %(prog)s --clouds-json-dir stage/ --cloudx-jira CLOUDX-123 --ami-adc-release-date 2024-12-01
  %(prog)s --clouds-json-dir /path/to/json/files --cloudx-jira CLOUDX-456 --image-dir /path/to/images --output-dir ./output

  # Combine existing pub-mapfile JSON files from multiple cloudx-jira releases:
  %(prog)s --combine-image-releases-path ./dist/pub-mapfile/2024-12-01

Output files will be created in: {output-dir}/{ami-adc-release-date}/{rhel-version}-{cloudx-jira}/{region}/
Combined files will be created in: {combine-image-releases-path}/combined/{region}/
        """
    )
    parser.add_argument('--clouds-json-dir', '-c',
                        help='Path to directory containing *.json files to process (required for generation mode)',
                        required=False)
    parser.add_argument('--cloudx-jira', '-j',
                        help='CLOUDX JIRA ID for the image release (e.g., CLOUDX-123) (required for generation mode)',
                        required=False)
    parser.add_argument('--ami-adc-release-date', '-r',
                        help='AMI ADC release date in YYYY-MM-DD format (default: today)',
                        default=datetime.now().strftime('%Y-%m-%d'))
    parser.add_argument('--image-dir', '-i',
                        help='Optional directory containing image files for MD5 verification',
                        default=None)
    parser.add_argument('--output-dir', '-o',
                        help='Base directory for output files. Files will be written to {output-dir}/{ami-adc-release-date}/{rhel-version}-{cloudx-jira}/{region}/ (default: ./dist/pub-mapfile)',
                        default='./dist/pub-mapfile')
    parser.add_argument('--combine-image-releases-path', '-C',
                        help='Path to existing release directory containing multiple {rhel-version}-{cloudx-jira} subdirectories to combine into consolidated files per region. When specified, combines existing JSON files instead of processing clouds.json files.',
                        default=None)

    args = parser.parse_args()

    # Validate arguments based on mode
    if args.combine_image_releases_path:
        # Combine mode - only combine_image_releases_path is required
        combine_json_files(args.combine_image_releases_path)
        return
    else:
        # Generation mode - clouds_json_dir and cloudx_jira are required
        if not args.clouds_json_dir:
            parser.error("--clouds-json-dir is required for generation mode")
        if not args.cloudx_jira:
            parser.error("--cloudx-jira is required for generation mode")

    # Read all *.json files from directory
    clouds_data = []
    json_pattern = os.path.join(args.clouds_json_dir, "*.json")
    json_files = glob.glob(json_pattern)

    if not json_files:
        print(f"Error: No *.json files found in directory {args.clouds_json_dir}")
        sys.exit(1)

    print(f"Found {len(json_files)} JSON files in {args.clouds_json_dir}")

    for json_file in json_files:
        try:
            with open(json_file, 'r') as f:
                file_data = json.load(f)

                # Ensure file_data is a list
                if isinstance(file_data, list):
                    clouds_data.extend(file_data)
                    print(f"  Loaded {len(file_data)} images from {os.path.basename(json_file)}")
                else:
                    print(f"Warning: {json_file} does not contain a list, skipping")

        except FileNotFoundError:
            print(f"Error: {json_file} not found")
            sys.exit(1)
        except json.JSONDecodeError as e:
            print(f"Error parsing JSON from {json_file}: {e}")
            sys.exit(1)
        except Exception as e:
            print(f"Error reading {json_file}: {e}")
            sys.exit(1)

    print(f"Total images loaded: {len(clouds_data)}")

    # Select images that contain "us-east-1-hourly" in dest attribute
    # and exclude SAP images
    filtered_images = [
        image for image in clouds_data
        if (
            (
                (isinstance(image.get('dest', []), list) and 'us-east-1-hourly' in image.get('dest', [])) or
                (isinstance(image.get('dest', []), str) and image.get('dest', []) == 'us-east-1-hourly')
            )
            and image.get('build_info', {}).get('name', '') != 'rhel-sap-ec2'
        )
    ]

    print(f"Found {len(filtered_images)} images with 'us-east-1-hourly' in dest attribute (excluding SAP)\n")

    if not filtered_images:
        print("Error:No images found matching the filter criteria. Exiting.")
        sys.exit(1)

    # Transform images to pub-mapfile format
    transformed_files = []
    for image in filtered_images:
        transformed = transform_image_to_pubmapfile_format(image, args.image_dir)
        transformed_files.append(transformed)

    print(f"Total images transformed: {len(transformed_files)}\n")

    # Create the pub-mapfile structure
    pub_mapfile = {
        "header": {
            "version": "0.2"
        },
        "payload": {
            "files": transformed_files
        }
    }

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Extract RHEL major version from first transformed object for cloudx-jira prefix
    if transformed_files:
        release_version = transformed_files[0]['attributes']['release']['version']
        # Extract major version (e.g., "9.4.0" -> "9")
        major_version = release_version.split('.')[0]
        rhel_version = f"rhel{major_version}"
    else:
        # unknown RHEL version
        print("Warning: RHEL version not found in the first transformed file, using 'rhel' as the version prefix")
        rhel_version = "rhel"

    # Define the three regions to generate files for
    regions = ["us-east-1", "us-iso-east-1", "us-isob-east-1"]

    # Generate files for each region
    for region in regions:
        # Create region-specific versions of the data
        region_pub_mapfile = copy.deepcopy(pub_mapfile)
        region_test_pub_mapfile = copy.deepcopy(pub_mapfile)

        # Update region in all file entries
        for file_entry in region_pub_mapfile['payload']['files']:
            file_entry['attributes']['region'] = region

        for file_entry in region_test_pub_mapfile['payload']['files']:
            file_entry['attributes']['region'] = region
            file_entry['attributes']['billing_codes'] = {
                "codes": [],
                "name": "HourlyTest"
            }

        # Create directory structure: {output-dir}/{ami-adc-release-date}/{rhel-version}-{cloudx-jira}/{region}
        region_output_dir = os.path.join(args.output_dir, args.ami_adc_release_date, f"{rhel_version}-{args.cloudx_jira}", region)
        if not os.path.exists(region_output_dir):
            os.makedirs(region_output_dir)

        # Generate filenames
        output_filename = f"pub-mapfile-{timestamp}.json"
        test_output_filename = f"test-pub-mapfile-{timestamp}.json"

        output_path = os.path.join(region_output_dir, output_filename)
        test_output_path = os.path.join(region_output_dir, test_output_filename)

        # Write both output files for this region
        try:
            # Write main pub-mapfile
            with open(output_path, 'w') as f:
                json.dump(region_pub_mapfile, f, indent=2)
            print(f"Successfully created {output_path} with {len(transformed_files)} image files")

            # Write test pub-mapfile
            with open(test_output_path, 'w') as f:
                json.dump(region_test_pub_mapfile, f, indent=2)
            print(f"Successfully created {test_output_path} with {len(transformed_files)} image files (test version)")

        except Exception as e:
            print(f"Error writing output files for region {region}: {e}")
            continue

    # Print SHA256 checksums for all transformed files (only if image_dir was provided)
    if args.image_dir:
        print(f"\nImage file SHA256 checksums for use in transfer ticket:")
        for file_entry in transformed_files:
            if file_entry.get('sha256sum'):
                filename = os.path.basename(file_entry.get('relative_path'))
                print(f"{file_entry['sha256sum']}  {filename}")

if __name__ == "__main__":
    main()