#!/bin/bash
#
# Generated by Claude 4 Sonnet
#
set -e

# Script configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$SCRIPT_DIR/lib"
VENV_NAME=".venv-pubtools"

echo "Installing pubtools-adc (OFFLINE MODE)..."
echo "This will install pubtools-adc and all its dependencies from bundled wheels."
echo "Working directory: $SCRIPT_DIR"
echo "Wheels directory: $LIB_DIR"
echo

# Check if lib directory exists and has wheels
if [[ ! -d "$LIB_DIR" ]]; then
    echo "ERROR: Library directory not found: $LIB_DIR"
    echo "Please run the build script first to create the offline package."
    exit 1
fi

WHEEL_COUNT=$(find "$LIB_DIR" -name "*.whl" | wc -l)
if [[ $WHEEL_COUNT -eq 0 ]]; then
    echo "ERROR: No wheel files found in $LIB_DIR"
    echo "Please run the build script first to download dependencies."
    exit 1
fi

echo "Found $WHEEL_COUNT wheel files in $LIB_DIR"

# Check if we're in a virtual environment
if [[ "$VIRTUAL_ENV" != "" ]]; then
    echo "Using existing virtual environment: $VIRTUAL_ENV"
else
    echo "Creating virtual environment: $VENV_NAME"
    python3 -m venv "$VENV_NAME"

    # Activate the virtual environment
    source "$VENV_NAME/bin/activate"
    echo "Virtual environment created and activated"
fi

# Install all wheels from the lib directory (offline mode)
echo "Installing all dependencies and pubtools-adc from bundled wheels..."
echo "Using offline installation (no internet required)..."

# Use --find-links to point to our lib directory and --no-index for offline mode
pip install --no-index --find-links "$LIB_DIR" "$LIB_DIR"/*.whl

# Verify installation
echo
echo "Verifying installation..."
if pubtools-adc-push --help > /dev/null 2>&1; then
    echo "✓ pubtools-adc-push command is available"

    # Get version info
    VERSION=$(python -c "import pkg_resources; print(pkg_resources.get_distribution('pubtools-adc').version)" 2>/dev/null || echo "unknown")
    echo "✓ pubtools-adc version: $VERSION"
else
    echo "✗ Error: pubtools-adc-push command not found"
    echo "Installation may have failed."
    exit 1
fi

echo
echo "🎉 Installation complete!"
echo "================================"
echo "✓ All dependencies installed from bundled wheels (no internet required)"
echo "✓ Total wheels installed: $WHEEL_COUNT"
echo "✓ Installation directory: $VIRTUAL_ENV"

echo
echo "📋 To use pubtools-adc:"
echo "  source $VIRTUAL_ENV/bin/activate"
echo "  pubtools-adc-push --help"
echo
echo "📋 pubtools-adc-push is now available in your current environment"

echo
echo "🚀 Ready to use!"
